name: Build and Push Docker Image to GHCR

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers workflow only when there is a semantic tag pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from tag
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/} # Removes the refs/tag/ so we only get the version
        echo "VERSION=$VERSION" >> $GITHUB_ENV 
        echo "Extracted version: $VERSION"

    - name: Build Docker image
      run: |
        docker build --no-cache -t ghcr.io/alledarw/devops3/web-server-nginx:${{ env.VERSION }} .
        echo "Built Docker image with version: ${{ env.VERSION }}"

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/alledarw/devops3/web-server-nginx:${{ env.VERSION }}
        echo "Pushed Docker image with version: ${{ env.VERSION }}"
